### ISSUE TITLE
qt5-base-git package in ArchLinux repository does not conflict with qt5-base

### ISSUE THREAD

**Issue by jkcdarunday** [papyros/papyros#11]
The qt5-base-git package in ArchLinux repository does not conflict with qt5-base when it should.

```
Repository     : papyros
Name           : qt5-base-git
Version        : v5.4.1.1254.gb678445-1
Description    : A cross-platform application and UI framework
Architecture   : x86_64
URL            : https://qt-project.org/
Licenses       : GPL3  LGPL
Groups         : None
Provides       : qt5-base
Depends On     : dbus  xcb-util-keysyms  xcb-util-wm  xcb-util-image  libxext  inputproto  libgl  libxkbcommon  systemd  libpng  sqlite  fontconfig  icu  libxrender
Optional Deps  : qtchooser: set the default Qt toolkit
                 postgresql-libs: PostgreSQL driver
                 libmariadbclient: MariaDB driver
                 unixodbc: ODBC driver
                 libfbclient: Firebird/iBase driver
Conflicts With : None
Replaces       : None
Download Size  :  11.24 MiB
Installed Size :  54.02 MiB
Packager       : Unknown Packager
Build Date     : Thursday, 05 March, 2015 08:37:37 AM PHT
Validated By   : MD5 Sum  SHA256 Sum
```

This causes it to have file conflicts with qt5-base and fail to install.

```
skeithc@xelor ~ % pacman -S qt5-base-git        
resolving dependencies...
looking for conflicting packages...

Package (1)           New Version             Net Change

papyros/qt5-base-git  v5.4.1.1254.gb678445-1   54.02 MiB

Total Installed Size:  54.02 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                       [######################################################################] 100%
(1/1) checking package integrity                                                                                     [######################################################################] 100%
(1/1) loading package files                                                                                          [######################################################################] 100%
(1/1) checking for file conflicts                                                                                    [######################################################################] 100%
error: failed to commit transaction (conflicting files)
qt5-base-git: /usr/bin/moc exists in filesystem
qt5-base-git: /usr/bin/qdbuscpp2xml exists in filesystem
qt5-base-git: /usr/bin/qdbusxml2cpp exists in filesystem
qt5-base-git: /usr/bin/qdoc exists in filesystem
...
```

**Comment by pandada8** [comment]
+1

**Comment by iBelieve** [comment]
We have a new build server and the [PKGBUILD for qt-base-git](https://github.com/papyros/repository/blob/testing/packages/qt5-base-git/PKGBUILD) should be fixed now.

**Comment by the-glu** [comment]
The problem is still present :(

```
sudo pacman -S papyros-shell
résolution des dépendances...
recherche des conflits entre paquets...
:: qt5-base-git et qt5-base sont en conflit. Supprimer qt5-base ? [o/N] o
:: qt5-declarative-git et qt5-declarative sont en conflit. Supprimer qt5-declarative ? [o/N] o
:: qt5-xmlpatterns-git et qt5-xmlpatterns sont en conflit. Supprimer qt5-xmlpatterns ? [o/N] o
:: qt5-quickcontrols-git et qt5-quickcontrols sont en conflit. Supprimer qt5-quickcontrols ? [o/N] o
:: qt5-graphicaleffects-git et qt5-graphicaleffects sont en conflit. Supprimer qt5-graphicaleffects ? [o/N] o
:: qt5-svg-git et qt5-svg sont en conflit. Supprimer qt5-svg ? [o/N] o
:: kactivities-frameworks et kactivities4 sont en conflit. Supprimer kactivities4 ? [o/N] o

Paquets (27) greenisland-git-20150618.4855207-1  kactivities-frameworks-5.11.0-1  kactivities4-4.13.3-1 [suppression]  kcmutils-5.11.0-1  kdeclarative-5.11.0-1  kpackage-5.11.0-1  libqtxdg-1.2.0-1  modemmanager-qt-5.11.0-1
             networkmanager-qt-5.11.0-1  plasma-framework-5.11.0-2  plasma-nm-5.3.1-1  qml-extras-0.1.r1.g41ec929-1  qml-material-0.1.r19.gb382e69-1  qt5-base-5.4.2-1 [suppression]  qt5-base-git-v5.5.0.beta1.345.g56aad2a-1
             qt5-declarative-5.4.2-1 [suppression]  qt5-declarative-git-v5.5.0.beta1.48.g9dee99e-1  qt5-graphicaleffects-5.4.2-1 [suppression]  qt5-graphicaleffects-git-v5.5.0.beta1-1  qt5-quickcontrols-5.4.2-1 [suppression]
             qt5-quickcontrols-git-v5.5.0.beta1.23.g234dc90-1  qt5-svg-5.4.2-1 [suppression]  qt5-svg-git-v5.5.0.beta1-1  qt5-wayland-dev-git-5.5.0.beta1.r25.ge890425-1  qt5-xmlpatterns-5.4.2-1 [suppression]
             qt5-xmlpatterns-git-v5.5.0.beta1.2.g25ad8b7-1  papyros-shell-0.0.5.r100.ga381c4f-1

Taille totale installée :     114.23 MiB
Taille de mise à jour nette :   37.65 MiB

:: Procéder à l’installation ? [O/n] 
(20/20) vérification des clés dans le trousseau                                                                                                [#######################################################################################] 100%
(20/20) vérification de l’intégrité des paquets                                                                                                [#######################################################################################] 100%
(20/20) chargement des fichiers des paquets                                                                                                    [#######################################################################################] 100%
(20/20) analyse des conflits entre fichiers                                                                                                    [#######################################################################################] 100%
erreur : la validation de la transaction a échoué (conflit de fichiers)
qt5-base-git : /usr/bin/moc est déjà présent dans le système de fichiers
qt5-base-git : /usr/bin/qdbuscpp2xml est déjà présent dans le système de fichiers
qt5-base-git : /usr/bin/qdbusxml2cpp est déjà présent dans le système de fichiers
qt5-base-git : /usr/bin/qdoc est déjà présent dans le système de fichiers
qt5-base-git : /usr/bin/qlalr est déjà présent dans le système de fichiers
qt5-base-git : /usr/bin/qmake est déjà présent dans le système de fichiers
qt5-base-git : /usr/bin/rcc est déjà présent dans le système de fichiers
qt5-base-git : /usr/bin/uic est déjà présent dans le système de fichiers
Des erreurs se sont produites, aucun paquet n’a été mis à jour.
```

**Comment by the-glu** [comment]
Additionnal remark: Thoses files bellongs to `qtchooser 48-1`, who is required by `qt5-base`

**Comment by akazantsev** [comment]
```
$ sudo pacman -S papyros-shell
resolving dependencies...
looking for conflicting packages...
:: qt5-base-git and qt5-base are in conflict. Remove qt5-base? [y/N] y
:: qt5-declarative-git and qt5-declarative are in conflict. Remove qt5-declarative? [y/N] y
:: qt5-xmlpatterns-git and qt5-xmlpatterns are in conflict. Remove qt5-xmlpatterns? [y/N] y
:: qt5-quickcontrols-git and qt5-quickcontrols are in conflict. Remove qt5-quickcontrols? [y/N] y
:: qt5-graphicaleffects-git and qt5-graphicaleffects are in conflict. Remove qt5-graphicaleffects? [y/N] y
:: qt5-svg-git and qt5-svg are in conflict. Remove qt5-svg? [y/N] y

Packages (22) greenisland-git-20150625.9b6c062-1  libqtxdg-1.2.0-2
              modemmanager-qt-5.12.0-1  networkmanager-qt-5.12.0-1
              plasma-framework-5.12.0-1  plasma-nm-5.3.2-1
              qml-extras-0.1.r1.g41ec929-1  qml-material-0.1.r23.g3c640c3-1
              qt5-base-5.5.0-1 [removal]
              qt5-base-git-v5.5.0.beta1.362.gec8c1dc-1
              qt5-declarative-5.5.0-1 [removal]
              qt5-declarative-git-v5.5.0.19.ga3f686c-1
              qt5-graphicaleffects-5.5.0-1 [removal]
              qt5-graphicaleffects-git-v5.5.0.1.gb4ef5a9-1
              qt5-quickcontrols-5.5.0-1 [removal]
              qt5-quickcontrols-git-v5.5.0.11.g56dfb59-1
              qt5-svg-5.5.0-1 [removal]  qt5-svg-git-v5.5.0.1.g93d77ed-1
              qt5-wayland-dev-git-5.5.0.r17.g05ea6b9-1
              qt5-xmlpatterns-5.5.0-1 [removal]
              qt5-xmlpatterns-git-v5.5.0.3.g69c5390-1
              papyros-shell-0.0.5.r108.g430bba7-1

Total Download Size:     3.75 MiB
Total Installed Size:  110.48 MiB
Net Upgrade Size:       28.88 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages ...
 plasma-framework-5....     3.3 MiB  2.59M/s 00:01 [######################] 100%
 modemmanager-qt-5.1...   147.7 KiB   762K/s 00:00 [######################] 100%
 networkmanager-qt-5...   322.9 KiB  1125K/s 00:00 [######################] 100%
(16/16) checking keys in keyring                   [######################] 100%
(16/16) checking package integrity                 [######################] 100%
(16/16) loading package files                      [######################] 100%
(16/16) checking for file conflicts                [######################] 100%
error: failed to commit transaction (conflicting files)
qt5-base-git: /usr/bin/moc exists in filesystem
qt5-base-git: /usr/bin/qdbuscpp2xml exists in filesystem
qt5-base-git: /usr/bin/qdbusxml2cpp exists in filesystem
qt5-base-git: /usr/bin/qdoc exists in filesystem
qt5-base-git: /usr/bin/qlalr exists in filesystem
qt5-base-git: /usr/bin/qmake exists in filesystem
qt5-base-git: /usr/bin/rcc exists in filesystem
qt5-base-git: /usr/bin/uic exists in filesystem
Errors occurred, no packages were upgraded.
```

The problem is still there. Anyway do really you need Qt5 from git now? Qt 5.5.0 in upstream will papyros with it?

**Comment by Krakers665** [comment]
Have the same problem
